/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PrivacidadeMetaAppRouteImport } from './routes/privacidade-meta-app'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermosDeServicoRouteImport } from './routes/termos-de-servico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeMetaAppRoute = PrivacidadeMetaAppRouteImport.update({
  id: '/privacidade-meta-app',
  path: '/privacidade-meta-app',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeServicoRoute = TermosDeServicoRouteImport.update({
  id: '/termos-de-servico',
  path: '/termos-de-servico',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/privacidade-meta-app': typeof PrivacidadeMetaAppRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/privacidade-meta-app': typeof PrivacidadeMetaAppRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/privacidade-meta-app': typeof PrivacidadeMetaAppRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/politica-de-privacidade'
    | '/privacidade-meta-app'
    | '/sitemap.xml'
    | '/termos-de-servico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/politica-de-privacidade'
    | '/privacidade-meta-app'
    | '/sitemap.xml'
    | '/termos-de-servico'
  id:
    | '__root__'
    | '/'
    | '/politica-de-privacidade'
    | '/privacidade-meta-app'
    | '/sitemap.xml'
    | '/termos-de-servico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PrivacidadeMetaAppRoute: typeof PrivacidadeMetaAppRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosDeServicoRoute: typeof TermosDeServicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade-meta-app': {
      id: '/privacidade-meta-app'
      path: '/privacidade-meta-app'
      fullPath: '/privacidade-meta-app'
      preLoaderRoute: typeof PrivacidadeMetaAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-servico': {
      id: '/termos-de-servico'
      path: '/termos-de-servico'
      fullPath: '/termos-de-servico'
      preLoaderRoute: typeof TermosDeServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PrivacidadeMetaAppRoute: PrivacidadeMetaAppRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosDeServicoRoute: TermosDeServicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
